#!/usr/bin/env bash
# Configure your Nginx server to another page.

strold="server_name _;"
strnew="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i -e "s|$strold|$strnew|" /etc/nginx/sites-enabled/default
