#!/usr/bin/env bash
# This script displays a string infinitely
invincible()
{
    echo "I am invincible!!!"
}

trap invincible SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
