#!/usr/bin/env bash
# This script displays "Best School" 10 times (but prints something extra on the 9th iteration) using a while loop and an if statement
ntimes=0
while [ $ntimes -lt 10 ]
do
    echo "Best School"
    ntimes=$(( ntimes + 1 ))

    if [ $ntimes == 9 ]
    then
        echo "Hi"
    fi
done
