#!/usr/bin/env bash
# This script displays "Best School" 10 times except for the 4th and 8th iteration.
ntimes=0
while [ $ntimes -lt 10 ]
do
    ntimes=$(( ntimes + 1 ))

    if [ $ntimes == 4 ]
    then
        echo "bad luck"
    elif [ $ntimes == 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
